api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from api import views


router = DefaultRouter()
router.register("articles", views.ArticleViewSet, basename="articles")
router.register("users", views.UserViewSet, basename="users")
"""
/articles/ - GET / List
/articles/ - POST / Create
/articles/<int:pk>/ - GET / Read
/articles/<int:pk>/ - DELETE / Delete
/articles/<int:pk>/ - PUT / Update
"""


urlpatterns = [
    path("", include(router.urls)),
    path("sign-up", views.RegisterView.as_view(), name="all-articles"),
]

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path("articles/", views.ArticleListView.as_view(), name="all-articles"),
    path("articles/<int:pk>/", views.ArticleDetailView.as_view(), name="get-articles"),
]

site_z38_2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("user_profile.urls")),
    path("api/", include("api.urls")),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path

from user_profile import views

urlpatterns = [
    path("<str:username>/", views.UserDetailView.as_view(), name="user-profile"),
    path("<str:username>/edit/", views.UserUpdateView.as_view(), name="edit-profile"),
    path(
        "<str:username>/delete/", views.UserDeleteView.as_view(), name="delete-profile"
    ),
]

home/models.py
from django.contrib.auth.models import User
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    avatar = models.ImageField(upload_to="images", null=True)

    def __repr__(self):
        return f"{self.title} - {self.content[:50]}"

    def __str__(self):
        return f"{self.title} - {self.content[:50]}"


class Image(models.Model):
    image = models.ImageField(upload_to="images", null=True)
    article = models.ForeignKey("Article", on_delete=models.CASCADE)

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    country = models.CharField(max_length=30, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.user.username

api/views.py
from django.contrib.auth.models import User

from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.viewsets import ModelViewSet
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.pagination import LimitOffsetPagination

from home.models import Article

from api.pagination import CustomPageNumberPagination
from api.permissions import IsAuthorOrReadOnly
from api.serializers import ArticleSerializer, UserSerializer, RegisterSerializer


class ArticleViewSet(ModelViewSet):
    # permission_classes = (IsAuthenticated, IsAuthorOrReadOnly)
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer
    pagination_class = CustomPageNumberPagination
    filter_backends = (SearchFilter, OrderingFilter)
    search_fields = ("title", "content")


class UserViewSet(ModelViewSet):
    permission_classes = (IsAdminUser,)
    queryset = User.objects.all()
    serializer_class = UserSerializer
    lookup_field = "username"
    pagination_class = LimitOffsetPagination


class RegisterView(CreateAPIView):
    serializer_class = RegisterSerializer

home/views.py
from django.views.generic import ListView, DetailView

from home.models import Article


class ArticleListView(ListView):
    model = Article
    template_name = "articles.html"
    ordering = "title"
    context_object_name = "articles"


class ArticleDetailView(DetailView):
    model = Article
    template_name = "article.html"
    slug_field = "pk"
    context_object_name = "obj"

user_profile/views.py
from django.contrib.auth.models import User

from django.views.generic import DetailView, DeleteView, UpdateView

from home.models import Article


class UserDetailView(DetailView):
    model = User
    template_name = "user/profile.html"
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "user"

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context["articles"] = Article.objects.filter(author=context["user"])
        return context


class UserUpdateView(UpdateView):
    model = User
    template_name = "user/edit_profile.html"
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "user"
    fields = ["username", "first_name", "last_name"]
    success_url = "/articles/"


class UserDeleteView(DeleteView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "user/delete_profile.html"
    success_url = "/articles/"
    context_object_name = "user"

templates/article.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<link rel="stylesheet" href="{% static 'main.css' %}">

<body>
    <div>
        <a href="{{ obj.pk }}">Ссылка</a>
        <b>{{ obj.title }}</b>
        <p>{{ obj.content }}</p>
        {% if obj.image %}
        <img src="{{ obj.image.url }}" alt="">
        {% endif %}
    </div>
    <hr>
</body>
</html>

templates/articles.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All article</title>
</head>
<body>
    <!-- Image and text -->
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-top">
          Bootstrap
        </a>
      </div>
    </nav>

    <div class="container">
        <div class="row">
            {% for article in articles %}
                <div class="col-4">
                    <a class="btn btn-primary"
                       href="{{ article.pk }}"
                       role="button"
                    >
                        Ссылка
                    </a>
                    <b>{{ article.title }}</b>
                    <p>{{ article.content }}</p>
                    <h1>avatar:</h1>
                    {% if article.avatar %}
                    <img src="{{ article.avatar.url }}" alt="">
                    {% endif %}
                    {% for image in article.image_set.all %}
                        <img src="{{ image.image.url }}" alt="">
                    {% endfor %}
                    <hr>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</html>

templates/user/delete_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Удалить пользователя "{{ user.username }}"</button>
            </form>
        </div>
    </div>
</body>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</html>

templates/user/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User profile</title>
</head>
<body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-top">
          Bootstrap
        </a>
      </div>
    </nav>

    <h1>Форма для редактирования данных пользователя {{ user.get_full_name }}</h1>

    <div class="container">
        <div class="row">
            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="username" class="form-label">Username</label>
                  <input name="username" type="text" class="form-control" id="username" placeholder="enter username" value="{{ user.username }}">
                </div>
                <div class="mb-3">
                  <label for="first_name" class="form-label">First name</label>
                  <input name="first_name" type="text" class="form-control" id="first_name" placeholder="Enter first name" value="{{ user.first_name }}">
                </div>
                <div class="mb-3">
                  <label for="last_name" class="form-label">Last name</label>
                  <input name="last_name" type="text" class="form-control" id="last_name" placeholder="Enter last name" value="{{ user.last_name }}">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

</body>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</html>

templates/user/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User profile</title>
</head>
<body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-top">
          Bootstrap
        </a>
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <a href="{{ user.username }}">Ссылка</a>
            <b>{{ user.username }}</b>
            <p>{{ user.get_full_name }}</p>
            <p>Телефон: {{ user.profile.phone }}</p>
            <p>Страна: {{ user.profile.country }}</p>
            <a class="btn btn-primary"
               href="/{{ user.username }}/edit/"
               role="button">Редактировать юзера</a>
            <a role="button" class="btn btn-danger" href="/{{ user.username }}/delete/">
                Удалить пользователя "{{ user.username }}"
            </a>
            <h3>User articles:</h3>
            {% for article in articles %}
                <div class="card" style="width: 18rem;">
                  <img src="https://i.imgur.com/sTmQ0AM.jpg" class="card-img-top">
                  <div class="card-body">
                    <h5 class="card-title">{{ article.title}}</h5>
                    <p class="card-text">{{ article.content }}</p>
                    <a href="{% url 'get-articles' pk=article.pk %}" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
            {% endfor %}
        </div>
    </div>

</body>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</html>

templates/user/successfully_delete_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DELETE</title>
</head>
<body>
    <h1>Пользователь успешно удален</h1>
</body>
</html>